import pandas as pd

# Loading sample sheet and configuration
samples = pd.read_csv("/array-1/users/acharya/data/sample_sheet.csv")
input_dir = "/array-1/data/raw/240502_SN417_0543_A_HT5THDMXY/raw"
fastqc_dir = "results/fastqc"
clipped_dir = "results/clipped"
adapter_seq = "TACACGACGCTCTTCCGATCT"

sample_list = [file.split(".fastq.gz")[0] for file in samples['file']]

# getting fastq file paths
def get_fastq(wildcards):
    return f"{input_dir}/{wildcards.sample}.fastq.gz"

#define final output file for trimmed
def get_final_outputs():
    return expand(f"{clipped_dir}/{{sample}}_clipped.fastq.gz", sample=sample_list)

#rule all for fastqc and cutadapt
rule all:
    input:
        get_final_outputs()

rule fastqc:
    input:
        get_fastq
    output:
        report=directory(f"{fastqc_dir}/{{sample}}/fastqc.html")
    threads: int(workflow.cores * 0.2)
    shell:
        "mkdir -p {output.report}; fastqc --nogroup --extract --quiet --threads {threads} -o {output.report} {input}"

rule cutadapt:
    input:
        get_fastq
    output:
        clipped=f"{clipped_dir}/{{sample}}_clipped.fastq.gz"
    threads: 1
    shell:
        "cutadapt -e 0.25 -a {adapter_seq} -o {output.clipped} {input}"
